
name: Linting CI

on:
  pull_request:
  push:
    branches: master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Python version
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - name: Create and start virtual environment
      run: |
        python3 -m venv venv
        source venv/bin/activate

    - name: Install dependencies
      run: pip install -r devrequirements.txt

    - name: Run pre-commit hooks
      run: SKIP=flake8 pre-commit run --all-files

    - name: Run flake8
      run: "flake8 \
      --format='::error file=%(path)s,line=%(row)d,col=%(col)d::[flake8] %(code)s: %(text)s'"
